object Versions {
  lazy val akkaHttpVersion       = "10.2.10"
  lazy val akkaManagementVersion = "1.1.4"
  lazy val akkaVersion           = "2.6.20"
  lazy val catsVersion           = "2.8.0"
  lazy val jacksonVersion        = "2.11.4"
  lazy val json4sVersion         = "4.0.6"
  lazy val logbackVersion        = "1.4.4"
  lazy val mustacheVersion       = "0.9.10"
  lazy val openapi4jVersion      = "1.0.7"
  lazy val scalaMockVersion      = "5.2.0"
  lazy val scalapbVersion        = "0.11.1"
  lazy val scalatestVersion      = "3.2.14"
  lazy val tikaVersion           = "2.5.0"
}

object PagopaVersions {
  lazy val commonsVersion               = "1.0.x-SNAPSHOT"
  lazy val agreementProcessVersion      = "1.0.x-SNAPSHOT"
  lazy val catalogManagementVersion     = "1.0.x-SNAPSHOT"
  lazy val catalogProcessVersion        = "1.0.x-SNAPSHOT"
  lazy val partyProcessVersion          = "1.0.x-SNAPSHOT"
  lazy val partyManagementVersion       = "1.0.x-SNAPSHOT"
  lazy val tenantManagementVersion      = "1.0.x-SNAPSHOT"
  lazy val tenantProcessVersion         = "1.0.x-SNAPSHOT"
  lazy val purposeProcessVersion        = "1.0.x-SNAPSHOT"
  lazy val userRegistryVersion          = "1.0.x-SNAPSHOT"
  lazy val attributeRegistryVersion     = "1.0.x-SNAPSHOT"
  lazy val authorizationProcessVersion  = "PIN-1315-SNAPSHOT"//"1.0.x-SNAPSHOT"
  lazy val selfcareV2ClientVersion      = "1.0.x-SNAPSHOT"
}